import React, { useState } from 'react';
import { useSensory } from '../context/SensoryContext';

/**
 * SessionDebrief Component (Phase 6 Reflection & Session Debrief)
 * Provides a calm, mechanics-focused end-of-session debrief with zero grades, scores, or confetti.
 * Includes interactive Session Timeline, Export options (Markdown & PDF), and Real-World Checklist.
 */
export const SessionDebrief = () => {
  const { lowStimulation, activeScenario, messages, resetPracticeSession, navigateTo } = useSensory();

  // Static Scenario Real-World Checklists
  const REAL_WORLD_CHECKLISTS = {
    accommodations: [
      "I know what specific adjustment or timeline I want to request.",
      "I know what outcome I'm hoping for.",
      "I'm ready with a backup option if they ask for compromise.",
      "I know my next clarifying question.",
      "I can pause or ask for written confirmation if I need to."
    ],
    plan_change: [
      "I know what transition steps would help me adjust to the new plan.",
      "I can explain what part of the change feels most urgent.",
      "I know what support or written instructions I need.",
      "I am prepared to ask for a buffer time before starting.",
      "I can pause the discussion if overwhelmed."
    ],
    boundary: [
      "I know my firm boundary line without over-explaining.",
      "I am ready if they ask a second time.",
      "I have a clear, respectful 'no' prepared.",
      "I know what alternative time or resource I can suggest.",
      "I can step away from the conversation if needed."
    ],
    custom: [
      "I know what I want to ask.",
      "I know what outcome I'm hoping for.",
      "I'm ready if they say no.",
      "I know my next question.",
      "I can pause if I need to."
    ]
  };

  const currentScenarioKey = activeScenario?.scenarioId || 'accommodations';
  const checklistItems = REAL_WORLD_CHECKLISTS[currentScenarioKey] || REAL_WORLD_CHECKLISTS.custom;

  // Interactive Checklist State
  const [checkedItems, setCheckedItems] = useState({});

  const toggleCheck = (idx) => {
    setCheckedItems(prev => ({
      ...prev,
      [idx]: !prev[idx]
    }));
  };

  // Mock / Derived Debrief Data
  const journeySteps = [
    "Started by introducing the practice scenario.",
    "Clarified specific needs and constraints during dialogue.",
    "Explored communication paths to reach mutual understanding.",
    "Completed rehearsal exchange."
  ];

  const patterns = [
    { title: "Clear Requests", description: "You stated your personal needs clearly during dialogue." },
    { title: "Acknowledging Responses", description: "You recognized your partner's constraints before replying." }
  ];

  const pathsUsed = ["Balanced", "Gentle"];

  const takeaways = [
    "Stating specific timelines helps reduce uncertainty.",
    "Acknowledging situational constraints keeps conversations constructive."
  ];

  const nextFocus = [
    "Try experimenting with the Direct communication path in your next rehearsal.",
    "Practice stating boundary expectations earlier in the discussion."
  ];

  // Visual Session Timeline Data
  const timelineEvents = [
    { label: "Started Practice Session", icon: "🏁", detail: "Initial rehearsal" },
    { label: "Perspective Viewed", icon: "👁️", detail: "Checked partner situational constraints" },
    { label: "Communication Path Selected", icon: "💬", detail: "Explored Balanced & Gentle paths" },
    { label: "Pause & Reset Used", icon: "⏸️", detail: "Paced conversation carefully" },
    { label: "Completed Practice", icon: "✅", detail: "Rehearsal finished" }
  ];

  // Export to Markdown (.md)
  const exportMarkdown = () => {
    const mdContent = `
# MindMirror AI - Practice Session Reflection
**Scenario:** ${activeScenario?.scenarioId || 'Practice Rehearsal'}
**Date:** ${new Date().toLocaleDateString()}

## Conversation Journey
${journeySteps.map((step, i) => `${i + 1}. ${step}`).join('\n')}

## Communication Patterns Observed
${patterns.map(p => `- **${p.title}:** ${p.description}`).join('\n')}

## Communication Paths Used
${pathsUsed.map(p => `- ${p}`).join('\n')}

## Practice Takeaways
${takeaways.map(t => `- ${t}`).join('\n')}

## Next Practice Focus
${nextFocus.map(f => `- ${f}`).join('\n')}

## Real-World Preparation Checklist
${checklistItems.map((item, i) => `[${checkedItems[i] ? 'X' : ' '}] ${item}`).join('\n')}

*Generated by MindMirror AI — Communication Pacing & Support*
`.trim();

    const blob = new Blob([mdContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `MindMirror_Reflection_${activeScenario?.scenarioId || 'session'}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Export to PDF / Print Layout
  const exportPDF = () => {
    window.print();
  };

  return (
    <div className="max-w-4xl mx-auto py-6 px-4 space-y-6">
      
      {/* Top Header Card */}
      <div className="glass-card rounded-2xl p-6 shadow-sm border border-border space-y-2">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <span className="text-xs font-bold text-text-accent uppercase tracking-wider block">
              End-of-Session Reflection
            </span>
            <h1 className="text-xl sm:text-2xl font-bold text-text-primary">
              Conversation Journey &amp; Debrief
            </h1>
          </div>

          <div className="flex items-center space-x-2">
            <button
              type="button"
              onClick={exportMarkdown}
              className="px-3.5 py-1.5 bg-bg-card hover:bg-bg-hover text-text-primary border border-border rounded-xl text-xs font-semibold focus:outline-none cursor-pointer"
            >
              📥 Export Markdown (.md)
            </button>
            <button
              type="button"
              onClick={exportPDF}
              className="px-3.5 py-1.5 bg-accent hover:bg-accent-hover text-white rounded-xl text-xs font-semibold focus:outline-none cursor-pointer"
            >
              🖨️ Export PDF
            </button>
          </div>
        </div>

        <p className="text-xs text-text-muted">
          Scenario: <strong className="text-text-primary uppercase">{currentScenarioKey}</strong> • Practice duration: ~3 mins • Total exchanges: {Math.max(1, Math.floor(messages.length / 2))}
        </p>
      </div>

      {/* 1. Conversation Journey (Visual Step Sequence) */}
      <div className="glass-card rounded-2xl p-5 border border-border space-y-3">
        <h2 className="text-xs font-bold text-text-primary uppercase tracking-wider flex items-center gap-1.5">
          🗺️ Conversation Journey
        </h2>

        <div className="grid grid-cols-1 sm:grid-cols-4 gap-2 text-xs">
          {journeySteps.map((step, idx) => (
            <div key={idx} className="p-3 bg-bg-card rounded-xl border border-border/50 space-y-1 relative">
              <span className="text-[10px] font-bold text-text-accent block">Step {idx + 1}</span>
              <p className="text-text-primary leading-relaxed">{step}</p>
            </div>
          ))}
        </div>
      </div>

      {/* 2. Communication Patterns & Paths Used */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Patterns */}
        <div className="glass-card rounded-2xl p-5 border border-border space-y-3">
          <h2 className="text-xs font-bold text-text-primary uppercase tracking-wider">
            💬 Communication Patterns Observed
          </h2>
          <div className="space-y-2">
            {patterns.map((p, idx) => (
              <div key={idx} className="p-3 bg-bg-card rounded-xl border border-border/50">
                <span className="font-bold text-text-primary block text-xs mb-0.5">{p.title}</span>
                <p className="text-xs text-text-secondary">{p.description}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Communication Paths Used */}
        <div className="glass-card rounded-2xl p-5 border border-border space-y-3">
          <h2 className="text-xs font-bold text-text-primary uppercase tracking-wider">
            🧭 Communication Paths Explored
          </h2>
          <p className="text-xs text-text-muted">
            Communication styles used during this practice rehearsal (No scores or percentages):
          </p>

          <div className="flex flex-wrap gap-2 pt-1">
            {pathsUsed.map((path, idx) => (
              <span
                key={idx}
                className="px-3 py-1.5 bg-accent-soft text-text-accent border border-accent/40 rounded-xl text-xs font-semibold"
              >
                {path} Path
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* 3. Practice Takeaways & Next Practice Focus */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="glass-card rounded-2xl p-5 border border-border space-y-3">
          <h2 className="text-xs font-bold text-text-primary uppercase tracking-wider">
            💡 Practice Takeaways
          </h2>
          <div className="space-y-2 text-xs">
            {takeaways.map((t, idx) => (
              <div key={idx} className="p-3 bg-bg-card rounded-xl border border-border/40 text-text-primary flex items-start gap-2">
                <span>•</span>
                <span>{t}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="glass-card rounded-2xl p-5 border border-border space-y-3">
          <h2 className="text-xs font-bold text-text-primary uppercase tracking-wider">
            🎯 Next Practice Focus
          </h2>
          <p className="text-xs text-text-muted">Suggestions to experiment with next time:</p>
          <div className="space-y-2 text-xs">
            {nextFocus.map((f, idx) => (
              <div key={idx} className="p-3 bg-bg-card rounded-xl border border-border/40 text-text-primary flex items-start gap-2">
                <span>→</span>
                <span>{f}</span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* 4. Interactive Session Timeline */}
      <div className="glass-card rounded-2xl p-5 border border-border space-y-3">
        <h2 className="text-xs font-bold text-text-primary uppercase tracking-wider">
          ⏳ Session Activity Timeline
        </h2>

        <div className="flex flex-wrap items-center gap-2 text-xs pt-1">
          {timelineEvents.map((evt, idx) => (
            <React.Fragment key={idx}>
              <div className="p-2.5 bg-bg-card border border-border/60 rounded-xl flex items-center gap-2">
                <span>{evt.icon}</span>
                <div>
                  <span className="font-semibold text-text-primary block text-[11px]">{evt.label}</span>
                  <span className="text-[10px] text-text-muted">{evt.detail}</span>
                </div>
              </div>
              {idx < timelineEvents.length - 1 && (
                <span className="text-text-muted font-bold text-xs">➔</span>
              )}
            </React.Fragment>
          ))}
        </div>
      </div>

      {/* 5. Demo-Ending Feature: Real-World Preparation Checklist */}
      <div className="glass-card rounded-2xl p-6 border-2 border-accent/40 bg-accent-soft/20 space-y-4">
        <div className="flex items-center justify-between border-b border-accent/30 pb-2">
          <div>
            <span className="text-[10px] font-bold text-text-accent uppercase tracking-wider block">
              Demo-Ending Preparation Tool
            </span>
            <h3 className="text-base font-bold text-text-primary">
              📋 Real-World Readiness Checklist
            </h3>
          </div>
          <span className="text-xs text-text-muted italic">Before your real conversation</span>
        </div>

        <p className="text-xs text-text-muted">
          Check off items as you prepare to hold this conversation in real life:
        </p>

        <div className="space-y-2.5 text-xs">
          {checklistItems.map((item, idx) => {
            const isChecked = !!checkedItems[idx];
            return (
              <label
                key={idx}
                onClick={() => toggleCheck(idx)}
                className={`flex items-start gap-3 p-3 rounded-xl border cursor-pointer transition-colors ${
                  isChecked
                    ? 'bg-accent-soft border-accent text-text-primary font-medium'
                    : 'bg-bg-card border-border/60 hover:bg-bg-hover text-text-secondary'
                }`}
              >
                <input
                  type="checkbox"
                  checked={isChecked}
                  onChange={() => {}}
                  className="mt-0.5 rounded text-accent focus:ring-accent"
                />
                <span className={isChecked ? 'line-through opacity-80' : ''}>{item}</span>
              </label>
            );
          })}
        </div>
      </div>

      {/* Action CTA Buttons */}
      <div className="flex items-center justify-between pt-2">
        <button
          type="button"
          onClick={() => navigateTo('progress')}
          className="px-4 py-2.5 bg-bg-card hover:bg-bg-hover text-text-secondary border border-border rounded-xl text-xs font-semibold cursor-pointer"
        >
          View Progress Dashboard
        </button>

        <button
          type="button"
          onClick={() => {
            resetPracticeSession();
            navigateTo('practice');
          }}
          className="px-6 py-3 bg-accent hover:bg-accent-hover text-white text-xs sm:text-sm font-semibold rounded-xl cursor-pointer btn-press shadow-sm"
        >
          🔄 Practice Scenario Again
        </button>
      </div>

    </div>
  );
};
